"""Add plot and comment to Movie

Revision ID: 010454673089
Revises: 4576dce07089
Create Date: 2026-09-06 16:36:16.803747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010454673089'
down_revision = '4576dce07089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plot', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('plot')

    # ### end Alembic commands ###
