"""Add is_favorite to Movie

Revision ID: 451fd7b6107c
Revises: 1dd5e626df2b
Create Date: 2026-09-06 16:09:33.417307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451fd7b6107c'
down_revision = '1dd5e626df2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('is_favorite')

    # ### end Alembic commands ###
