"""Add watched_on_platform to Movie

Revision ID: 4576dce07089
Revises: 451fd7b6107c
Create Date: 2026-09-06 16:22:16.127873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4576dce07089'
down_revision = '451fd7b6107c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watched_on_platform', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('watched_on_platform')

    # ### end Alembic commands ###
