"""Add Friend and MovieRecommendation tables

Revision ID: 62c12869e7dc
Revises: cdde35c0cfcc
Create Date: 2026-09-06 17:20:47.915449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c12869e7dc'
down_revision = 'cdde35c0cfcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_via_email', sa.Boolean(), nullable=True),
    sa.Column('invited_via_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('linked_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=False),
    sa.Column('movie_title', sa.String(length=120), nullable=False),
    sa.Column('movie_year', sa.String(length=10), nullable=True),
    sa.Column('movie_poster', sa.String(length=255), nullable=True),
    sa.Column('movie_rating', sa.String(length=10), nullable=True),
    sa.Column('movie_plot', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie_recommendations')
    op.drop_table('friends')
    # ### end Alembic commands ###
