"""Adiciona genero ao filme e a indicacao de filme

Revision ID: c849640691cd
Revises: 62c12869e7dc
Create Date: 2026-09-07 18:45:51.603281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c849640691cd'
down_revision = '62c12869e7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_genre', sa.String(length=150), nullable=True))

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('genre')

    with op.batch_alter_table('movie_recommendations', schema=None) as batch_op:
        batch_op.drop_column('movie_genre')

    # ### end Alembic commands ###
