"""Add plot_pt to Movie

Revision ID: cdde35c0cfcc
Revises: 010454673089
Create Date: 2026-09-06 16:43:54.087108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdde35c0cfcc'
down_revision = '010454673089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plot_pt', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('plot_pt')

    # ### end Alembic commands ###
